name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.algoramming.xyz
          username: frogbase@algoramming.xyz
          password: ${{ secrets.FROGBASE_FTP_PASSWORD }}
          local-dir: ./
          remote-dir: ./
